### ISSUE TITLE
Database migration tool for common database service

### ISSUE THREAD

**Issue by zheng1** [openpitrix/openpitrix#141]
We need a migration tool for initial and migrate database *[db-ctrl]*.
This is a vote issue for choose tools.

Optional:
https://github.com/mattes/migrate

**Comment by zheng1** [comment]
https://bitbucket.org/liamstask/goose/

**Comment by zheng1** [comment]
https://flywaydb.org/ [recommend from @martinyunify ]

**Comment by rayzhou2017** [comment]
what is the use case for OpenPitrix?

**Comment by zheng1** [comment]
@rayzhou2017 The last meeting we discussed the decision to select a database version control tool, rather than the code that we wrote our own SQL management.

**Comment by rayzhou2017** [comment]
Why we need a database version control tool? Is it a client tool to manage OpenPitrix database? What is the requirement?

**Comment by rayzhou2017** [comment]
OK, I understand this issue now. We had an agreement that we should develop a common service to manage database-related operations so that the services of OpenPitrix operate database such CRUD by calling this common service with passing parameters like database url, credential, table name etc. With this common service, the architecture
is clear, and development and maintenance is easier than each service containing its database operations.

**Comment by rayzhou2017** [comment]
Please make a vote everyone.

**Comment by martinyunify** [comment]
added db migration script in #159
