### ISSUE TITLE
Delete cluster immediately when the runtime is deleted

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/openpitrix#588]
When a runtime is deleted, clusters in the runtime can be delete without generate jobs and tasks.

**Comment by rayzhou2017** [comment]
What does this proposal mean? End user deregister her/his runtime in OpenPitrix, then delete her/his clusters in the runtime?

**Comment by rayzhou2017** [comment]
The logic seems unclear. How about this:
1. If there is any live cluster including active, stopped, suspended status, then prevent end user delete the runtime registration. End user must clean all live clusters before delete the registration.
2. However, end user can disable the runtime so that no new cluster can be created.

**Comment by chilianyi** [comment]
OK, the logic is reasonable.

Here is one situation, the runtime is not available already, so DeleteClusters will fail because send request to the runtime failed.
